# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jae Woo So
title: AI Research Engineer
email: nchos88@gmail.com
# email_title: Email (Email title override)
phone: (82)010-6355-6339
# phone_title: Phone (Phone title override)
website: https://jaewoo-so.github.io/sjw/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  jaewoo-so
stackoverflow_username: "JaeWoo So"
#dribbble_username: jekyll
3facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://#fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Investment model development & consulting
        description: | # this will include new lines to allow paragraphs
          신규 투자 모형 개발 : 인공지능 기술을 사용한 투자전략 연구/
          
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Investment model development & consulting
        description: | # this will include new lines to allow paragraphs
          - Development of new investment model: Research on investment strategy using artificial intelligence technology
      
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: ESG Media Classification System
        description: | # this will include new lines to allow paragraphs
          - Machine learning-based classification model research
          - Kubernetes based Restful API development
          
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Default Option System Development
        description: | # this will include new lines to allow paragraphs
          - Optimized design including own fund
          
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Investment model development & consulting
        description: | # this will include new lines to allow paragraphs
          신규 투자 모형 개발 : 인공지능 기술을 사용한 투자전략 연구/
          
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Investment model development & consulting
        description: | # this will include new lines to allow paragraphs
          신규 투자 모형 개발 : 인공지능 기술을 사용한 투자전략 연구
      
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Default Option System Development
        description: | # this will include new lines to allow paragraphs
          - 제약조건의 최적화 문제 해결
          - 단순 최적 수익률이 아닌, 자사 상품 판매 

  - title: Experience
    layout: list
    content:
      - layout: top-left
        title: Daishin Economic Research Institute
        sub_title: Job title
        caption: 2020.09 - present
        link: http://www.deri.co.kr/
        description: | # this will include new lines to allow paragraphs
          Worked on applying machine learning technology to financial engineering and ESG evaluation services.

          - Development of real-time news analysis system for ESG risk and classification
          - Corporate equity structure visualization modeling
          - Development of investment model based on machine learning model
          - Media data-based enterprise ESG risk prediction
          - Development of automatic collection and classification system for Fair Trade Commission deliberation and decision data

      - layout: left
        title: Threagen Bio
        sub_title: Job title
        caption: 2018.05 - 2020.08
        link: https://www.theragenbio.com/
        description: | # this will include new lines to allow paragraphs
          AI based R&D for omics , clinical, and medical image data. 

          - Predictive modeling based on genetic data. 
          - Predict patient drug responsiveness with clinical data.
          - Classification of cancer types by medical image data. 
          - Classification of health status with microbiome data.

  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Kyushu University
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
